### ISSUE TITLE
Es erscheint nur eine kaputte Seite

### ISSUE THREAD

**Issue by skerbis** [alexplusde/collect#10]
<img width="1353" alt="Bildschirmfoto 2022-06-03 um 16 04 33" src="https://user-images.githubusercontent.com/791247/171869857-d33e7863-d460-4227-b2c2-c41909cd12a8.png">

**Comment by alxndr-w** [comment]
Plugins installieren. Warum die README kaputt angezeigt wird, weiß ich nicht. #8

**Comment by skerbis** [comment]
Habe Video installiert , keine Änderung

**Comment by alxndr-w** [comment]
gefixt
